### ISSUE TITLE
Example error in section Greedy vs lazy matching

### ISSUE THREAD

**Issue by EdgarAllanzp** [zeeshanu/learn-regex#108]
<pre>
"/(.*at)/" => <a href="#learn-regex"><strong>The fat cat sat on the mat.</strong></a> </pre>

The example in doc should not match period character of the sentence.

It 's correct with the external example link in the doc.
https://regex101.com/r/AyAdgJ/1

**Comment by zeeshanu** [comment]
#109 Merged 👍
