### ISSUE TITLE
Bonus part issues

### ISSUE THREAD

**Issue by lnquy** [zeeshanu/learn-regex#12]
Hi @zeeshanu,
Thanks for the great project.
I think you should take a look on the [Bonus](https://github.com/zeeshanu/learn-regex#bonus) part again since there're some problems here:
1. US Phone Number: `^+?[\d\s]{3,}$` => `^\+?[\d\s-]{3,}$`
2. US Phone with code: `^+?[\d\s]+(?[\d\s]{10,}$` => I don't get it, but at least you need to escape `\+` and missing a `)` here.
3. Redundant parentheses:
Lowercase letters only: `^([a-z])*$` => `^[a-z]*$`
Uppercase letters only: `^([A-Z])*$` => `^[A-Z]*$`

**Comment by sparecycles** [comment]
Also, redundant character class brackets. ( `[[a-zA-Z0-9]\-\.]` should just be `[a-zA-Z0-9\-\.]`, etc... ).  This breaks functionality.

```javascript
$ node
> /^(((http|https|ftp):\/\/)?([[a-zA-Z0-9]\-\.])+(\.)([[a-zA-Z0-9]]){2,4}([[a-zA-Z0-9]\/+=%&_\.~?\-]*))*$/.test( 'https://github.com/zeeshanu/learn-regex' )
false
> /^(((http|https|ftp):\/\/)?([a-zA-Z0-9\-\.])+(\.)([a-zA-Z0-9]){2,4}([a-zA-Z0-9\/+=%&_\.~?\-]*))*$/.test( 'https://github.com/zeeshanu/learn-regex' )
true
```

**Comment by newmusicdownload** [comment]
Thanks for the great project.

**Comment by SahibYar** [comment]
bonus part has been deleted now 😞 😞 😞
