### ISSUE TITLE
Add Regex for #hashtag, @mention

### ISSUE THREAD

**Issue by JaleelNazir** [zeeshanu/learn-regex#13]
Can you please add regex for 

- #hashtag
- @mention

It will be very useful.

---Thanks in advance

**Comment by falaktheoptimist** [comment]
Anyone working on this one? If not, I can take up this one

**Comment by zeeshanu** [comment]
@falaktheoptimist Thanks for asking. :)
I am too busy to make a PR for this but you can make a PR i will merge it latter.
