### ISSUE TITLE
Positive Lookbehind example doesn't work correct

### ISSUE THREAD

**Issue by Imangazaliev** [zeeshanu/learn-regex#21]
Please check out this link: https://regex101.com/r/TZ8DOX/1/

**Comment by zeeshanu** [comment]
@Imangazaliev **regex101** uses javascript regular expression engine which does not support lookbehinds.

**Comment by Imangazaliev** [comment]
What about this?

![image](https://user-images.githubusercontent.com/11244193/28714854-fcd44d1e-739d-11e7-9f5c-1e92599c34bb.png)
