### ISSUE TITLE
Underscores and hyphens in image

### ISSUE THREAD

**Issue by thepill** [zeeshanu/learn-regex#22]
Hi,

![capture](https://user-images.githubusercontent.com/8901210/28669743-ac09dfb6-72d5-11e7-9990-58cd0a1acba6.PNG)

`Letters, numbers, underscore, hyphen` should be Letters, numbers, underscore**s**, hyphen**s**

**Comment by prabodhmeshram** [comment]
@thepill : Underscore and hyphen are only one of their kind. It is a single character symbol, rather than alphabets and numbers having multiple symbols.

**Comment by thepill** [comment]
@prabodhmeshram I think reading this implies that this will only match for a single underscore and hyphen.

**Comment by prabodhmeshram** [comment]
@thepill I see your point. But I think the author meant to imply that the mentioned regex pattern will match all small case letters, numbers including hyphen and underscore. As there is range mentioned for alphabets and numbers, so author want to refer a range of characters you can match. 

It doesn't even say it will match multiple alphabets and numbers. Just a basic example for newbies to make them understand the structure used in Regex. All the examples are given as the tutorial proceeds.

**Comment by thepill** [comment]
Good points - lets see what @zeeshanu thinks. Issue can just be closed if he thinks also like you :)

**Comment by prabodhmeshram** [comment]
Yeah hope so mate :)
