### ISSUE TITLE
Confusing example in 2.4 Braces

### ISSUE THREAD

**Issue by sunqingyao** [zeeshanu/learn-regex#26]
Referencing [2.4 Braces](https://github.com/zeeshanu/learn-regex#24-braces):

> 
> We can leave out the second number. For example, the regular expression `[0-9]{2,}` means: Match 2 or more digits. If we also remove the comma the regular expression `[0-9]{2}` means: Match exactly 2 digits.
> <pre>
> "[0-9]{2,}" => The number was 9.<a href="#learn-regex"><strong>9997</strong></a> but we rounded it off to <a href="#learn-regex"><strong>10</strong></a>.0.
> </pre>
> [Test the regular expression](https://regex101.com/r/Gdy4w5/1)
> <pre>
> "[0-9]{2}" => The number was 9.<a href="#learn-regex"><strong>99</strong></a><a href="#learn-regex"><strong>97</strong></a> but we rounded it off to <a href="#learn-regex"><strong>10</strong></a>.0.
> </pre>
> [Test the regular expression](https://regex101.com/r/gqajq8/1)

The substrings matched in both examples are identical, which is kind of confusing. Maybe we can change the example to `"[0-9]{3,}"` and `"[0-9]{3}"`, or something else.

**Comment by zeeshanu** [comment]
@sunqingyao The regular expression does not match same substrings in both examples. You can see `9997` are both colored same but however if you hover on to `9997` you will see the difference. Github markdown does not provide underline functionality inside pre tag so I add `href` link to matched text by which they are look alike.
