### ISSUE TITLE
正则报错

### ISSUE THREAD

**Issue by sijinglei** [zeeshanu/learn-regex#54]
手机国家号: ^+?[\d\s]{3,}$
手机号: ^+?[\d\s]+(?[\d\s]{10,}$

这两个正则都是错的。。。。

**Comment by LiuMengzhou** [comment]
@sijinglei I agree with you!
PS: English maybe more appropriate.

**Comment by LiuMengzhou** [comment]
> **Bonus**
> - US Phone Number: ^+?[\d\s]{3,}$
> - US Phone with code: ^+?[\d\s]+(?[\d\s]{10,}$
**pattern error**
