### ISSUE TITLE
Source of image in SVG format

### ISSUE THREAD

**Issue by ponsfrilus** [zeeshanu/learn-regex#68]
Dear all,
   I would like to share the SVG I've done for the French translation. Use the layers and ungroup everythings to be sure to be able to edit.

https://drive.google.com/drive/folders/0B2xIihFvGD2kYWo1ZmtNdXRld2M?usp=sharing

Disclaimer: I wasn't able to find the exact font - it would be great if someone can link it somewhere.

**Comment by eamanu** [comment]
Excelent!

It would be great if you can add a folder with the .svg and make a PR!

**Comment by ponsfrilus** [comment]
@emanu see #69

**Comment by ponsfrilus** [comment]
Merged.

**Comment by eamanu** [comment]
Great
