### ISSUE TITLE
WIP Russian translation

### ISSUE THREAD

**Issue by vitalkanev** [zeeshanu/learn-regex#70]
Hey! I'm now doing a Russian translation of this repository in my *own* fork (In the pinned repositories first).

**Note**
* I used `Vim` to edit the file and `Notepad++` to convert `CR LF` line ending to `LF` one

**Comment by zeeshanu** [comment]
@vitalkanev That's great :+1:

**Comment by Oire** [comment]
@vitalkanev, have you done a lot already? I'm just doing the same... :)

**Comment by eamanu** [comment]
@Oire @vitalkanev  You can share a branch in yours repos. Then one of you could make a PR.

**Comment by vitalkanev** [comment]
@eamanu I will add @Oire as collaborator on my fork

**Comment by vitalkanev** [comment]
Closing since it's not active (I archived repo)
