### ISSUE TITLE
Typo in regexp-en.png file

### ISSUE THREAD

**Issue by yuhwan** [zeeshanu/learn-regex#72]
The second square closing brace should be the curly brace to represent `quantifiers` properly. So, the regex should be `^[a-z0-9_-]{3,15}$` rather than `^[a-z0-9_-]{3,15]$`.

**Comment by ponsfrilus** [comment]
Thank, just seen that. See https://github.com/zeeshanu/learn-regex/pull/73/commits/5e40ce0b4dc78d026731001aecd38ea4f3576aef

**Comment by ponsfrilus** [comment]
Fixed in #77
