### ISSUE TITLE
hi , 前后关联约束(前后预查) 在javascript正则测试中报错

### ISSUE THREAD

**Issue by ZengLingYong** [zeeshanu/learn-regex#85]
前后关联约束的例子在线测试时，在javascript不通过
![image](https://user-images.githubusercontent.com/25698878/29648086-fb71c074-88be-11e7-8ef0-2faabf2f521f.png)

是什么原因呢？

**Comment by zeeshanu** [comment]
@ZengLingYong The regular expression defined in Positive Lookbehind section will not work in Javascript. Because javascript regex engine does not support Positive Lookbehind.
